# Generated by Django 3.0.6 on 2020-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
