# Generated by Django 3.0.6 on 2020-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
