# Generated by Django 3.0.4 on 2020-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_list_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
