# Generated by Django 3.0.6 on 2020-05-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0004_list_created_on'),
        ('playlist_app', '0002_list_created_on'),
    ]

    operations = [
    ]
