# Generated by Django 3.0.6 on 2020-05-10 13:54

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0005_merge_20200510_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_on',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
