# Generated by Django 3.0.6 on 2020-05-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0003_auto_20200510_1210'),
        ('playlist_app', '0006_auto_20200510_1354'),
    ]

    operations = [
    ]
