language:
  python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: heroku
api_key:
  secure: <KEY>
app: playlist-web-project # Heroku app’s name
on:
  repo: ger4rdgg/playlist_projecte
  branch: master