language:
  python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: heroku
api_key:
  secure: <KEY>
app: personal-website-example # Heroku app’s name
on:
  repo: ferranverdes/rp-personal-website-example
  branch: master